spring:
  application:
    name: 'fornecedor'
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
server:
  port: 8081
