version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_forn
    ports:
      - "3307:3306"
    volumes:
      - /Users/flavio/workspace/alura/java/Docker/Volumes/MySql:/var/lib/mysql
